### ISSUE TITLE
Watchdog no longer works with latest releases

### ISSUE THREAD

**Issue by jstefanop** [Optiminer/OptiminerZcash#29] opened 2017-01-25 08:58 UTC
Watchdog in 1.5 no longer works (worked fine in 0.x releases. As soon as the watchdog script is called the miner freezes and the script is never executed (simple forced reboot script in my case).

**Comment by mrplow** [comment] 2017-01-26 21:09
Seeing the same issue
Ubuntu 16.04 server

**Comment by Optiminer** [comment] 2017-01-26 23:52
I will try to reproduce.

**Comment by Optiminer** [comment] 2017-01-27 00:24
Cannot reproduce, the script gets executed as intended:
[2017-01-27 01:22:59.424] [info] GPU0 Got work, start mining.
[2017-01-27 01:23:32.407] [error] GPU0 has not produced any solution in last 10! Executing "./watchdog-cmd.sh"
Uncomment any of the actions in 'watchdog-cmd.sh' to perform on stuck GPU!
[2017-01-27 01:23:33.424] [info] Got new work.
[2017-01-27 01:23:42.445] [error] GPU0 has not produced any solution in last 10! Executing "./watchdog-cmd.sh"
Uncomment any of the actions in 'watchdog-cmd.sh' to perform on stuck GPU!

**Comment by Optiminer** [comment] 2017-02-05 21:00
Closing as not reproducable.

**Closed by Optiminer** 2017-02-05 21:00 UTC
